---
title: "Extending Quarto"
---

## Description

{{< include _description.md >}}

## Setup

Please check the [Setup Instructions](setup.qmd) for recommended steps to take before the workshop.

## Schedule

| Time          | Activity         |
| :------------ | :--------------- |
| 09:00 - 10:30 | [Extension Basics](modules/01-basics.qmd)      |
| 10:30 - 11:00 | *Coffee break*   |
| 11:00 - 12:30 | Session 2        |
| 12:30 - 13:30 | *Lunch break*    |
| 13:30 - 15:00 | [Filters and Shortcodes](modules/03-filters.qmd)       |
| 15:00 - 15:30 | *Coffee break*   |
| 15:30 - 17:00 | Session 4        |

## Instructors

[Mine Çetinkaya-Rundel](https://mine-cr.com) is Professor of the Practice and the Director of Undergraduate Studies at the Department of Statistical Science and Developer Educator at Posit, PBC. Mine's work focuses on innovation in statistics and data science pedagogy, with an emphasis on computing, reproducible research, student-centered learning, and open-source education. [{{< iconify fa7-brands:linkedin >}}](https://www.linkedin.com/in/minec/) [{{< iconify fa7-brands:github >}}](https://github.com/mine-cetinkaya-rundel) 

[Charlotte Wickham](https://cwick.co.nz) (she/her) is a Developer Educator on the Developer Relations team at Posit with a focus on [Quarto](https://quarto.org). Prior to Posit, she taught Statistics and Data Science at Oregon State University where she received awards for her in-person and online teaching.  [{{< iconify fa7-brands:linkedin >}}](https://www.linkedin.com/in/cvwickham/) [{{< iconify fa7-brands:github >}}](https://github.com/cwickham) 

{{< include _license.md >}}
